name: "[cLabs] Test OpenVPN"

on:
  push:
    branches:
      - main
  # workflow_dispatch:

jobs:
  openvpn:
    permissions:
      contents: write
      actions: read
      pull-requests: write
      security-events: write
      attestations: write
      id-token: write
      repository-projects: write
    concurrency:
      group:   ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    uses: celo-org/reusable-workflows/.github/workflows/npm-publish.yaml@alvaro-npm-publish
    with:
      node-version: 20
      version-command: yarn versioning
      publish-command: yarn release
      # harden-runner: false

  test-outputs:
    needs: [openvpn]
    runs-on: ubuntu-latest
    steps:
      - name: Check outputs
        run: |
          echo "Outputs from openvpn job:"
          echo "version: ${{ needs.openvpn.outputs.publishedPackages }}"
          echo "version-tag: ${{ needs.openvpn.outputs.published }}"
